#spring:
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/shop
#    username: postgres
#    password: password
#  flyway:
#    baseline-on-migrate: true

spring.application.name=shop
spring.cloud.config.uri=http://localhost:8888
