server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ku78/config.git
          search-paths: config
          clone-on-start: true
  application:
    name: config_server

logging:
  level:
    org.springframework.cloud: DEBUG